services:
  autopartshop.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autopartshop.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - autopart_mssql_data:/var/opt/mssql
    restart: always
    
  # autopartshop.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=autopartshop.db,1433;Database=AutoPartShopDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
  #   ports:
  #     - "8080"
  #     - "8081"
  
volumes:
  autopart_mssql_data:
