services:
  autopartshop.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autopartshop.db
    
  # autopartshop.api:
  #   image: ${DOCKER_REGISTRY-}autopartshopapi
  #   depends_on:
  #     - autopartshop.db
  #   build:
  #     context: .
  #     dockerfile: src/AutoPartShop.Api/Dockerfile

volumes:
  autopart_mssql_data: