#base
FROM node:20-alpine AS build
WORKDIR /app

#build
ARG ENV_NAME=dev
ENV ENV_NAME=$ENV_NAME

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build -- --configuration=$ENV_NAME

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/autoweb/browser/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]