# DEVELOPMENT — local machine only.
# docker compose -f docker-compose.dev.yml up --build

services:
  autopartshop.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autopartshop.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"           # open for SSMS / DBeaver
    volumes:
      - autopart_mssql_dev_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' -No || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  autopartshop.api:
    build:
      context: ..
      dockerfile: src/AutoPartShop.Api/Dockerfile
    image: smapi:dev
    container_name: autopartshop.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AutoPartDb=Server=autopartshop.db,1433;Database=AutoPartShopDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - JwtSettings__SecretKey=YourSuperSecretKeyForJWTTokenGenerationMustBe32CharsLong!@#
      - JwtSettings__Issuer=AutoPartShopAPI
      - JwtSettings__Audience=AutoPartShopClient
      - JwtSettings__ExpiryInMinutes=60
      - JwtSettings__RefreshTokenExpiryInDays=7
    ports:
      - "5292:8080"           # open for Swagger / Postman
    depends_on:
      autopartshop.db:
        condition: service_healthy
    restart: unless-stopped

  autopartshop.web:
    build:
      context: ../src/AutoPartShop.WebApp
      dockerfile: dockerfile
      args:
        ENV_NAME: development  # sourceMap=true, optimization=false
    image: smweb:dev
    container_name: autopartshop.web
    ports:
      - "4200:80"
    depends_on:
      - autopartshop.api
    restart: unless-stopped

volumes:
  autopart_mssql_dev_data:
