import { test, expect } from '@playwright/test';

/**
 * Lighter smoke coverage for the remaining requested workflows: these pages are
 * populated as a side effect of the business-flow and POS specs (quick sales generate
 * invoices automatically), so the checks here focus on "the page loads, lists real
 * data, and a detail/report view renders" rather than driving a full create flow.
 */
test.describe('Invoices', () => {
    test('invoice list shows sales generated by earlier specs', async ({ page }) => {
        await page.goto('/sales/invoices');
        await expect(page.getByRole('heading', { name: 'Sales Invoices' })).toBeVisible();
        // At least one Paid invoice from the quick-sale specs should be listed.
        await expect(page.getByText('Paid').first()).toBeVisible();
    });

    test('opening an invoice shows its detail', async ({ page }) => {
        await page.goto('/sales/invoices');
        // Invoice numbers are plain table cells (not links) — the row itself navigates.
        const firstRow = page.getByRole('row', { name: /INV\d+/ }).first();
        const invoiceNumber = (await firstRow.getByText(/^INV\d+$/).innerText()).trim();
        await firstRow.click();
        await expect(page.getByText(invoiceNumber).first()).toBeVisible();
    });
});

test.describe('Reports', () => {
    test('reports hub loads with real totals', async ({ page }) => {
        await page.goto('/reports');
        await expect(page.getByRole('heading', { name: 'Reports' }).first()).toBeVisible();
        await expect(page.getByText('Gross Sales')).toBeVisible();
        await expect(page.getByRole('link', { name: /Sales Summary/ })).toBeVisible();
    });

    test('a report page renders its own data', async ({ page }) => {
        await page.goto('/reports');
        await page.getByRole('link', { name: /Sales Summary/ }).first().click();
        await expect(page.getByRole('heading', { name: 'Sales Summary' }).first()).toBeVisible();
        // The report's own period/orders table, not just the hub page shell.
        await expect(page.getByText('ORDERS', { exact: false }).first()).toBeVisible();
    });
});

test.describe('Warranty', () => {
    test('warranty registrations page loads', async ({ page }) => {
        await page.goto('/warranty');
        await expect(page.getByRole('heading', { name: 'Warranty Registrations' }).first()).toBeVisible();
        await expect(page.getByRole('button', { name: 'Register Warranty' })).toBeVisible();
    });
});
