namespace AutoPartShop.Application.Interfaces;

/// <summary>
/// Blob storage for uploaded files (product media, employee photos/documents).
/// Keys are provider-relative paths (e.g. "products/2026/07/{guid}.jpg") generated by the caller.
/// Implementations: local disk (default); an S3-compatible provider (Cloudflare R2 / MinIO)
/// can be added later without touching callers.
/// </summary>
public interface IFileStorageService
{
    Task SaveAsync(Stream content, string storageKey, string contentType, CancellationToken cancellationToken = default);

    /// <summary>Opens the blob for reading, or returns null when it does not exist.</summary>
    Task<Stream?> OpenReadAsync(string storageKey, CancellationToken cancellationToken = default);

    /// <summary>Deletes the blob; no-op when it does not exist.</summary>
    Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default);
}
