import { Component, inject, signal, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { CustomerService, CreateCustomerRequest } from '../services/customer.service';
import { I18nService } from '@/shared/services/i18n.service';
import { TranslatePipe } from '@/shared/pipes/translate.pipe';

@Component({
    selector: 'app-quick-customer-dialog',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, DialogModule, ButtonModule, InputTextModule, SelectModule, TranslatePipe],
    templateUrl: './quick-customer-dialog.component.html',
    styleUrl: './quick-customer-dialog.component.scss',
})
export class QuickCustomerDialogComponent {
    private readonly fb = inject(FormBuilder);
    private readonly customerService = inject(CustomerService);
    private readonly i18n = inject(I18nService);

    visible = signal(false);
    saving = signal(false);
    error = signal<string | null>(null);

    customerForm!: FormGroup;

    /** Getter, not a field: a field would freeze the labels in the language active at construction. */
    get customerTypes() {
        return [
            { label: this.i18n.t('quickCustomerDialog.types.individual'), value: 'INDIVIDUAL' },
            { label: this.i18n.t('quickCustomerDialog.types.business'), value: 'BUSINESS' },
            { label: this.i18n.t('quickCustomerDialog.types.dealer'), value: 'DEALER' },
            { label: this.i18n.t('quickCustomerDialog.types.wholesale'), value: 'WHOLESALE' }
        ];
    }

    // Output event when customer is created
    customerCreated = output<any>();

    constructor() {
        this.initializeForm();
    }

    initializeForm(): void {
        this.customerForm = this.fb.group({
            firstName: ['', [Validators.required, Validators.minLength(2)]],
            lastName: ['', []],
            phone: ['', [Validators.required]],
            email: ['', []],
            customerType: ['INDIVIDUAL'],
            city: [''],
            address: ['']
        });
    }

    open(): void {
        this.visible.set(true);
        this.customerForm.reset({ customerType: 'INDIVIDUAL' });
        this.error.set(null);
    }

    close(): void {
        this.visible.set(false);
    }

    onCancel(): void {
        this.close();
    }

    onSubmit(): void {
        if (this.customerForm.invalid) {
            Object.keys(this.customerForm.controls).forEach((key) => {
                this.customerForm.get(key)?.markAsTouched();
            });
            return;
        }

        this.saving.set(true);
        this.error.set(null);

        const formValue = this.customerForm.value;
        const request: CreateCustomerRequest = {
            customerCode: '', // Will be auto-generated by backend
            firstName: formValue.firstName,
            lastName: formValue.lastName,
            companyName: '',
            email: formValue.email || '',
            phone: formValue.phone,
            alternatePhone: '',
            billingAddress: formValue.address || '',
            shippingAddress: '',
            city: formValue.city || '',
            state: '',
            postalCode: '',
            country: '',
            customerType: formValue.customerType || 'INDIVIDUAL',
            primaryContactPerson: '',
            notes: ''
        };

        this.customerService.createCustomer(request).subscribe({
            next: (customer) => {
                this.customerCreated.emit(customer);
                this.saving.set(false);
                this.close();
            },
            error: (err) => {
                this.error.set(err.error?.message || this.i18n.t('quickCustomerDialog.createFailed'));
                this.saving.set(false);
                console.error('Error creating customer:', err);
            }
        });
    }
}
